### ISSUE TITLE
Ctrl + Alt + P triggers exception if password store is empty

### ISSUE THREAD

**Issue by rvernica** [Baggykiin/pass-winmenu#13]
I do not have any passwords stored yet. I get the following exception when pressing `Ctrl + Alt + P`:
![image](https://user-images.githubusercontent.com/241185/28506105-c2fc212a-6fdd-11e7-9f56-29051ddc8f04.png)
Here is the complete stack trace:
```C
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at PassWinmenu.Windows.PasswordSelectionWindow..ctor(IEnumerable`1 options, MainWindowConfiguration configuration)
   at PassWinmenu.Program.ShowPasswordMenu(IEnumerable`1 options)
   at PassWinmenu.Program.RequestPasswordFile()
   at PassWinmenu.Program.DecryptPassword(Boolean copyToClipboard, Boolean typeUsername, Boolean typePassword)
   at PassWinmenu.Program.<>c__DisplayClass14_0.<AssignHotkeys>b__0()
   at PassWinmenu.Hotkeys.HotkeyManager.HandleWndProc(Message& message)
   at PassWinmenu.Program.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
Once I add a password, the exception no longer occurs.

**Comment by Baggykiin** [comment]
3f6312b7e2de3af1065dd8aed6153e6772415a91 should fix this.
